dfs: dfs.c util.c
	cc util.c dfs.c util.h -std=c99 -o ../build/dfs.out

bfs: bfs.c util.c
	cc util.c bfs.c util.h -std=c99 -o ../build/bfs.out

dijkstra: dijkstra.c util.c
	cc util.c dijkstra.c util.h -std=c99 -o ../build/dijkstra.out

spfa: spfa.c util.c
	cc util.c spfa.c util.h -std=c99 -o ../build/spfa.out

astar: astar.c util.c
	cc util.c astar.c util.h -std=c99 -o ../build/astar.out

